import type { Manifest } from "./types";

/** Fetch the fixture manifest (generated by scripts/gen-fixture-manifest.mjs). */
export async function loadManifest(): Promise<Manifest> {
  const res = await fetch(`${import.meta.env.BASE_URL}fixtures.json`);
  if (!res.ok) throw new Error(`failed to load fixtures.json: ${res.status}`);
  return res.json() as Promise<Manifest>;
}
