import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// The @retrochains/* packages load their .wasm via `new URL('..._bg.wasm',
// import.meta.url)`; Vite resolves that to a bundled asset automatically. The
// fixture manifest is served from public/ (generated by scripts/gen-fixture-manifest.mjs).
export default defineConfig({
  plugins: [react()],
  // Workspace packages ship pre-built ESM + wasm; don't pre-bundle them (keeps
  // the `new URL(import.meta.url)` asset resolution intact).
  optimizeDeps: {
    exclude: ["@retrochains/bcc", "@retrochains/msc", "@retrochains/decompile"],
  },
});
